server:
  port: 8085
spring:
  application:
    name: storageservice #服务名称
  cloud:
    nacos:
      server-addr: localhost:8848 #nacos服务发现地址
      discovery:
#        ip: 175.178.85.36
        ip: localhost
        port: 8085
  datasource:
    druid:
      url: jdbc:mysql://175.178.85.36:3306/zhibo
      username: root
      password: hjc123
      driver-class-name: com.mysql.cj.jdbc.Driver
#配置redis
  redis:
    host: 175.178.85.36
    port: 6379
    jedis:
      pool:
        max-wait: 1ms #超时时间
        max-active: 8
        min-idle: 0 #最小空闲连接数
        max-idle: 4 #最大空闲连接数

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #在控制台输出sql信息
    map-underscore-to-camel-case: true #驼峰和下划线命名的匹配
  global-config:
    db-config:
      id-type: assign_id #使用雪花算法生成id