server:
  port: 8086
spring:
  application:
    name: interactionservice
  cloud:
    nacos:
      server-addr: localhost:8848 #服务发现地址
      discovery:
#        ip: 121.37.24.27
        ip: localhost
        port: 8086
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/zhibo
      username: root
      password: root
  redis:
    port: 6379
    host: localhost
    jedis:
      pool:
        max-idle: 4 #最大空闲连接数
        max-wait: 1ms #最大响应时间
        min-idle: 0 #最小空闲连接数
        max-active: 8 #最大连接数
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true #驼峰命名匹配
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #控制台输出mysql信息
  global-config:
    db-config:
      id-type: assign_id #使用雪花算法生成id